server:
  port: 8888

spring:
  application:
    name: air-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/odrianoaliveira/spring-cloud-config
          searchPaths: '{application}/{profile}'
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  user:
    name: root
    password: s3cr3t
